public class WithException{

    public static void main(String[] args) {
        throw new IllegalArgumentException("script failed for known reason");
    }

}